# Generated by Django 5.0.2 on 2024-03-07 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_alter_buyerprofilemodel_buyer'),
        ('seller', '0010_alter_product_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyercart', to='buyer.buyermodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartproduct', to='seller.product')),
            ],
        ),
    ]
