# Generated by Django 5.0.2 on 2024-03-11 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0005_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='seller',
        ),
    ]
