# Generated by Django 5.0.2 on 2024-03-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0006_remove_payment_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('canceled', 'Canceled'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
