# Generated by Django 5.0.2 on 2024-03-11 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0007_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
    ]
