# Generated by Django 5.0.2 on 2024-03-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofilemodel',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='seller_profile_pic/'),
        ),
    ]
