# Generated by Django 5.0.2 on 2024-03-02 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_sellerprofilemodel_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('pro_image', models.ImageField(upload_to='pro_image/')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('end_time', models.DateTimeField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Home', 'Home'), ('Furniture', 'Furniture'), ('Vehicle', 'Vehicle')], max_length=20)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.sellermodel')),
            ],
        ),
    ]
