# Generated by Django 5.0.2 on 2024-03-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_remove_product_end_time_product_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='min_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_image',
            field=models.ImageField(null=True, upload_to='pro_image/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
