# Generated by Django 5.0.2 on 2024-03-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0010_alter_product_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_closed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
