# Generated by Django 5.0.2 on 2024-03-11 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0012_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
