# Generated by Django 5.0.2 on 2024-03-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0013_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
